/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "ConfigApi.h"

#include <thrift/lib/cpp/TApplicationException.h>

namespace actor { namespace cpp2 {

template <typename ProtocolIn_, typename ProtocolOut_>
void ConfigApiAsyncProcessor::_processInThread_registerActorSystem(std::unique_ptr<apache::thrift::ResponseChannel::Request> req, std::unique_ptr<folly::IOBuf> buf, std::unique_ptr<ProtocolIn_> iprot, apache::thrift::Cpp2RequestContext* ctx, apache::thrift::async::TEventBase* eb, apache::thrift::concurrency::ThreadManager* tm) {
  auto pri = iface_->getprio_registerActorSystem(ctx);
  processInThread<ProtocolIn_, ProtocolOut_>(std::move(req), std::move(buf),std::move(iprot), ctx, eb, tm, pri, false, &ConfigApiAsyncProcessor::process_registerActorSystem<ProtocolIn_, ProtocolOut_>, this);
}

template <typename ProtocolIn_, typename ProtocolOut_>
void ConfigApiAsyncProcessor::process_registerActorSystem(std::unique_ptr<apache::thrift::ResponseChannel::Request> req, std::unique_ptr<folly::IOBuf> buf, std::unique_ptr<ProtocolIn_> iprot,apache::thrift::Cpp2RequestContext* ctx,apache::thrift::async::TEventBase* eb, apache::thrift::concurrency::ThreadManager* tm) {
  // make sure getConnectionContext is null
  // so async calls don't accidentally use it
  iface_->setConnectionContext(nullptr);
  ConfigApi_registerActorSystem_pargs args;
  std::unique_ptr< ::actor::cpp2::ActorInfo> uarg_info(new  ::actor::cpp2::ActorInfo());
  args.info = uarg_info.get();
  std::unique_ptr<apache::thrift::ContextStack> c(this->getContextStack(this->getServiceName(), "ConfigApi.registerActorSystem", ctx));
  try {
    deserializeRequest(args, buf.get(), iprot.get(), c.get());
  }
  catch (const std::exception& ex) {
    ProtocolOut_ prot;
    if (req) {
      LOG(ERROR) << ex.what() << " in function registerActorSystem";
      apache::thrift::TApplicationException x(apache::thrift::TApplicationException::TApplicationExceptionType::PROTOCOL_ERROR, ex.what());
      folly::IOBufQueue queue = serializeException("registerActorSystem", &prot, iprot->getSeqId(), nullptr, x);
      queue.append(apache::thrift::transport::THeader::transform(queue.move(), ctx->getTransforms(), ctx->getMinCompressBytes()));
      auto queue_mw = folly::makeMoveWrapper(std::move(queue));
      auto req_mw = folly::makeMoveWrapper(std::move(req));
      eb->runInEventBaseThread([=]() mutable {
        (*req_mw)->sendReply(queue_mw->move());
      }
      );
      return;
    }
    else {
      LOG(ERROR) << ex.what() << " in oneway function registerActorSystem";
    }
  }
  std::unique_ptr<apache::thrift::HandlerCallback<std::unique_ptr< ::actor::cpp2::ActorId>>> callback(new apache::thrift::HandlerCallback<std::unique_ptr< ::actor::cpp2::ActorId>>(std::move(req), std::move(c), return_registerActorSystem<ProtocolIn_,ProtocolOut_>, throw_registerActorSystem<ProtocolIn_, ProtocolOut_>, throw_wrapped_registerActorSystem<ProtocolIn_, ProtocolOut_>, iprot->getSeqId(), eb, tm, ctx));
  if (!callback->isRequestActive()) {
    callback.release()->deleteInThread();
    return;
  }
  ctx->setStartedProcessing();
  iface_->async_tm_registerActorSystem(std::move(callback), std::move(uarg_info));
}

template <class ProtocolIn_, class ProtocolOut_>
folly::IOBufQueue ConfigApiAsyncProcessor::return_registerActorSystem(int32_t protoSeqId, std::unique_ptr<apache::thrift::ContextStack> ctx,  ::actor::cpp2::ActorId const& _return) {
  ProtocolOut_ prot;
  ConfigApi_registerActorSystem_presult result;
  result.success = const_cast< ::actor::cpp2::ActorId*>(&_return);
  result.__isset.success = true;
  return serializeResponse("registerActorSystem", &prot, protoSeqId, ctx.get(), result);
}

template <class ProtocolIn_, class ProtocolOut_>
void ConfigApiAsyncProcessor::throw_registerActorSystem(std::unique_ptr<apache::thrift::ResponseChannel::Request> req,int32_t protoSeqId,std::unique_ptr<apache::thrift::ContextStack> ctx,std::exception_ptr ep,apache::thrift::Cpp2RequestContext* reqCtx) {
  ProtocolOut_ prot;
  ConfigApi_registerActorSystem_presult result;
  try {
    std::rethrow_exception(ep);
  }
  catch (const  ::actor::cpp2::RegisterException& e) {
    ctx->userException(folly::demangle(typeid(e)).toStdString());
    result.e = e;
    result.__isset.e = true;
  }
  catch (const std::exception& e) {
    if (req) {
      LOG(ERROR) << folly::exceptionStr(e).toStdString() << " in function registerActorSystem";
      apache::thrift::TApplicationException x(folly::exceptionStr(e).toStdString());
      ctx->userException(folly::demangle(typeid(e)).toStdString());
      folly::IOBufQueue queue = serializeException("registerActorSystem", &prot, protoSeqId, ctx.get(), x);
      queue.append(apache::thrift::transport::THeader::transform(queue.move(), reqCtx->getTransforms(), reqCtx->getMinCompressBytes()));
      req->sendReply(queue.move());
      return;
    }
    else {
      LOG(ERROR) << folly::exceptionStr(e).toStdString() << " in oneway function registerActorSystem";
    }
  }
  catch (...) {
    if (req) {
      LOG(ERROR) << "<unknown exception>" << " in function registerActorSystem";
      apache::thrift::TApplicationException x("<unknown exception>");
      folly::IOBufQueue queue = serializeException("registerActorSystem", &prot, protoSeqId, nullptr, x);
      queue.append(apache::thrift::transport::THeader::transform(queue.move(), reqCtx->getTransforms(), reqCtx->getMinCompressBytes()));
      req->sendReply(queue.move());
      return;
    }
    else {
      LOG(ERROR) << "<unknown exception>" << " in oneway function registerActorSystem";
    }
  }
  auto queue = serializeResponse("registerActorSystem", &prot, protoSeqId, ctx.get(), result);
  queue.append(apache::thrift::transport::THeader::transform(queue.move(), reqCtx->getTransforms(), reqCtx->getMinCompressBytes()));
  return req->sendReply(queue.move());
}

template <class ProtocolIn_, class ProtocolOut_>
void ConfigApiAsyncProcessor::throw_wrapped_registerActorSystem(std::unique_ptr<apache::thrift::ResponseChannel::Request> req,int32_t protoSeqId,std::unique_ptr<apache::thrift::ContextStack> ctx,folly::exception_wrapper ew,apache::thrift::Cpp2RequestContext* reqCtx) {
  if (!ew) {
    return;
  }
  ProtocolOut_ prot;
  ConfigApi_registerActorSystem_presult result;
  if (ew.with_exception< ::actor::cpp2::RegisterException>([&]( ::actor::cpp2::RegisterException& e) {
    ctx->userException(folly::demangle(typeid(e)).toStdString());
    result.e = e;
    result.__isset.e = true;
  }
  )) {} else
   {
    if (req) {
      LOG(ERROR) << ew.what().toStdString() << " in function registerActorSystem";
      apache::thrift::TApplicationException x(ew.what().toStdString());
      ctx->userException(ew.class_name().toStdString());
      folly::IOBufQueue queue = serializeException("registerActorSystem", &prot, protoSeqId, ctx.get(), x);
      queue.append(apache::thrift::transport::THeader::transform(queue.move(), reqCtx->getTransforms(), reqCtx->getMinCompressBytes()));
      req->sendReply(queue.move());
      return;
    }
    else {
      LOG(ERROR) << ew.what().toStdString() << " in oneway function registerActorSystem";
    }
  }
  auto queue = serializeResponse("registerActorSystem", &prot, protoSeqId, ctx.get(), result);
  queue.append(apache::thrift::transport::THeader::transform(queue.move(), reqCtx->getTransforms(), reqCtx->getMinCompressBytes()));
  return req->sendReply(queue.move());
}

template <typename Protocol_>
void ConfigApiAsyncClient::registerActorSystemT(Protocol_* prot, const apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const  ::actor::cpp2::ActorInfo& info) {
  std::unique_ptr<apache::thrift::ContextStack> ctx = this->getContextStack(this->getServiceName(), "ConfigApi.registerActorSystem", connectionContext_.get());
  ConfigApi_registerActorSystem_pargs args;
  args.info = const_cast< ::actor::cpp2::ActorInfo*>(&info);
  size_t bufSize = args.serializedSizeZC(prot);
  bufSize += prot->serializedMessageSize("registerActorSystem");
  folly::IOBufQueue queue(folly::IOBufQueue::cacheChainLength());
  prot->setOutput(&queue, bufSize);
  auto guard = folly::makeGuard([&]{prot->setOutput(nullptr);});
  try {
    ctx->preWrite();
    prot->writeMessageBegin("registerActorSystem", apache::thrift::T_CALL, 0);
    args.write(prot);
    prot->writeMessageEnd();
    ::apache::thrift::SerializedMessage smsg;
    smsg.protocolType = prot->protocolType();
    smsg.buffer = queue.front();
    ctx->onWriteData(smsg);
    ctx->postWrite(queue.chainLength());
  } catch(apache::thrift::TException &ex) {
    ctx->handlerError();
    throw;
  }
  auto eb = this->channel_->getEventBase();
  if(!eb || eb->isInEventBaseThread()) {
    this->channel_->sendRequest(rpcOptions, std::move(callback), std::move(ctx), queue.move());
  }
  else {
    auto mvCb = folly::makeMoveWrapper(std::move(callback));
    auto mvCtx = folly::makeMoveWrapper(std::move(ctx));
    auto mvBuf = folly::makeMoveWrapper(queue.move());
    eb->runInEventBaseThread([this, rpcOptions, mvCb, mvCtx, mvBuf] () mutable {
      this->channel_->sendRequest(rpcOptions, std::move(*mvCb), std::move(*mvCtx), std::move(*mvBuf));
    }
    );
  }
}

template <typename Protocol_>
folly::exception_wrapper ConfigApiAsyncClient::recv_wrapped_registerActorSystemT(Protocol_* prot,  ::actor::cpp2::ActorId& _return, ::apache::thrift::ClientReceiveState& state) {
  if (state.isException()) {
    return state.exceptionWrapper();
  }
  prot->setInput(state.buf());
  auto guard = folly::makeGuard([&] {prot->setInput(nullptr);});
  apache::thrift::ContextStack* ctx = state.ctx();
  std::string fname;
  int32_t protoSeqId = 0;
  apache::thrift::MessageType mtype;
  ctx->preRead();
  folly::exception_wrapper interior_ew;
  auto caught_ew = folly::try_and_catch<apache::thrift::TException, apache::thrift::protocol::TProtocolException>([&]() {
    prot->readMessageBegin(fname, mtype, protoSeqId);
    if (mtype == apache::thrift::T_EXCEPTION) {
      apache::thrift::TApplicationException x;
      x.read(prot);
      prot->readMessageEnd();
      interior_ew = folly::make_exception_wrapper<apache::thrift::TApplicationException>(x);
      return; // from try_and_catch
    }
    if (mtype != apache::thrift::T_REPLY) {
      prot->skip(apache::thrift::protocol::T_STRUCT);
      prot->readMessageEnd();
      interior_ew = folly::make_exception_wrapper<apache::thrift::TApplicationException>(apache::thrift::TApplicationException::TApplicationExceptionType::INVALID_MESSAGE_TYPE);
      return; // from try_and_catch
    }
    if (fname.compare("registerActorSystem") != 0) {
      prot->skip(apache::thrift::protocol::T_STRUCT);
      prot->readMessageEnd();
      interior_ew = folly::make_exception_wrapper<apache::thrift::TApplicationException>(apache::thrift::TApplicationException::TApplicationExceptionType::WRONG_METHOD_NAME);
      return; // from try_and_catch
    }
    ::apache::thrift::SerializedMessage smsg;
    smsg.protocolType = prot->protocolType();
    smsg.buffer = state.buf();
    ctx->onReadData(smsg);
    ConfigApi_registerActorSystem_presult result;
    result.success = &_return;
    result.read(prot);
    prot->readMessageEnd();
    ctx->postRead(state.buf()->length());
    if (result.__isset.success) {
      // _return pointer has been filled
      return; // from try_and_catch
    }
    if (result.__isset.e) {
      interior_ew = folly::make_exception_wrapper< ::actor::cpp2::RegisterException>(result.e);
      return; // from try_and_catch
    }
    else {
      interior_ew = folly::make_exception_wrapper<apache::thrift::TApplicationException>(apache::thrift::TApplicationException::TApplicationExceptionType::MISSING_RESULT, "failed: unknown result");
      return; // from try_and_catch
    }
  }
  );
  if (interior_ew || caught_ew) {
    ctx->handlerError();
    return interior_ew ? interior_ew : caught_ew;
  }
  return folly::exception_wrapper();
}

template <typename Protocol_>
void ConfigApiAsyncClient::recv_registerActorSystemT(Protocol_* prot,  ::actor::cpp2::ActorId& _return, ::apache::thrift::ClientReceiveState& state) {
  auto ew = recv_wrapped_registerActorSystemT(prot, _return, state);
  if (ew) {
    ew.throwException();
  }
}

template <class Protocol_>
uint32_t ConfigApi_registerActorSystem_pargs::read(Protocol_* iprot) {
  uint32_t xfer = 0;
  std::string fname;
  apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using apache::thrift::TProtocolException;


  while (true) {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == apache::thrift::protocol::T_STOP) {
      break;
    }
    if (fid == std::numeric_limits<int16_t>::min()) {
      if (fname == "info") {
        fid = 1;
        ftype = apache::thrift::protocol::T_STRUCT;
      }
    }
    switch (fid) {
      case 1:
      {
        if (ftype == apache::thrift::protocol::T_STRUCT) {
          xfer += ::apache::thrift::Cpp2Ops<  ::actor::cpp2::ActorInfo>::read(iprot, &(*const_cast< ::actor::cpp2::ActorInfo*>(this->info)));
          this->__isset.info = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      }
      default:
      {
        xfer += iprot->skip(ftype);
        break;
      }
    }
    xfer += iprot->readFieldEnd();
  }
  xfer += iprot->readStructEnd();

  return xfer;
}

template <class Protocol_>
uint32_t ConfigApi_registerActorSystem_pargs::serializedSize(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("ConfigApi_registerActorSystem_pargs");
  xfer += prot_->serializedFieldSize("info", apache::thrift::protocol::T_STRUCT, 1);
  xfer += ::apache::thrift::Cpp2Ops<  ::actor::cpp2::ActorInfo>::serializedSize(prot_, &(*const_cast< ::actor::cpp2::ActorInfo*>(this->info)));
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t ConfigApi_registerActorSystem_pargs::serializedSizeZC(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("ConfigApi_registerActorSystem_pargs");
  xfer += prot_->serializedFieldSize("info", apache::thrift::protocol::T_STRUCT, 1);
  xfer += ::apache::thrift::Cpp2Ops<  ::actor::cpp2::ActorInfo>::serializedSizeZC(prot_, &(*const_cast< ::actor::cpp2::ActorInfo*>(this->info)));
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t ConfigApi_registerActorSystem_pargs::write(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("ConfigApi_registerActorSystem_pargs");
  xfer += prot_->writeFieldBegin("info", apache::thrift::protocol::T_STRUCT, 1);
  xfer += ::apache::thrift::Cpp2Ops<  ::actor::cpp2::ActorInfo>::write(prot_, &(*const_cast< ::actor::cpp2::ActorInfo*>(this->info)));
  xfer += prot_->writeFieldEnd();
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

template <class Protocol_>
uint32_t ConfigApi_registerActorSystem_presult::read(Protocol_* iprot) {
  uint32_t xfer = 0;
  std::string fname;
  apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using apache::thrift::TProtocolException;


  while (true) {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == apache::thrift::protocol::T_STOP) {
      break;
    }
    if (fid == std::numeric_limits<int16_t>::min()) {
      if (fname == "success") {
        fid = 0;
        ftype = apache::thrift::protocol::T_STRUCT;
      }
      else if (fname == "e") {
        fid = 1;
        ftype = apache::thrift::protocol::T_STRUCT;
      }
    }
    switch (fid) {
      case 0:
      {
        if (ftype == apache::thrift::protocol::T_STRUCT) {
          xfer += ::apache::thrift::Cpp2Ops<  ::actor::cpp2::ActorId>::read(iprot, &(*const_cast< ::actor::cpp2::ActorId*>(this->success)));
          this->__isset.success = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      }
      case 1:
      {
        if (ftype == apache::thrift::protocol::T_STRUCT) {
          xfer += ::apache::thrift::Cpp2Ops<  ::actor::cpp2::RegisterException>::read(iprot, &this->e);
          this->__isset.e = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      }
      default:
      {
        xfer += iprot->skip(ftype);
        break;
      }
    }
    xfer += iprot->readFieldEnd();
  }
  xfer += iprot->readStructEnd();

  return xfer;
}

template <class Protocol_>
uint32_t ConfigApi_registerActorSystem_presult::serializedSize(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("ConfigApi_registerActorSystem_presult");
  if (this->__isset.success) {
    xfer += prot_->serializedFieldSize("success", apache::thrift::protocol::T_STRUCT, 0);
    xfer += ::apache::thrift::Cpp2Ops<  ::actor::cpp2::ActorId>::serializedSize(prot_, &(*const_cast< ::actor::cpp2::ActorId*>(this->success)));
  }
  else if (this->__isset.e) {
    xfer += prot_->serializedFieldSize("e", apache::thrift::protocol::T_STRUCT, 1);
    xfer += ::apache::thrift::Cpp2Ops<  ::actor::cpp2::RegisterException>::serializedSize(prot_, &this->e);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t ConfigApi_registerActorSystem_presult::serializedSizeZC(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("ConfigApi_registerActorSystem_presult");
  if (this->__isset.success) {
    xfer += prot_->serializedFieldSize("success", apache::thrift::protocol::T_STRUCT, 0);
    xfer += ::apache::thrift::Cpp2Ops<  ::actor::cpp2::ActorId>::serializedSizeZC(prot_, &(*const_cast< ::actor::cpp2::ActorId*>(this->success)));
  }
  else if (this->__isset.e) {
    xfer += prot_->serializedFieldSize("e", apache::thrift::protocol::T_STRUCT, 1);
    xfer += ::apache::thrift::Cpp2Ops<  ::actor::cpp2::RegisterException>::serializedSizeZC(prot_, &this->e);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t ConfigApi_registerActorSystem_presult::write(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("ConfigApi_registerActorSystem_presult");
  if (this->__isset.success) {
    xfer += prot_->writeFieldBegin("success", apache::thrift::protocol::T_STRUCT, 0);
    xfer += ::apache::thrift::Cpp2Ops<  ::actor::cpp2::ActorId>::write(prot_, &(*const_cast< ::actor::cpp2::ActorId*>(this->success)));
    xfer += prot_->writeFieldEnd();
  }
  else if (this->__isset.e) {
    xfer += prot_->writeFieldBegin("e", apache::thrift::protocol::T_STRUCT, 1);
    xfer += ::apache::thrift::Cpp2Ops<  ::actor::cpp2::RegisterException>::write(prot_, &this->e);
    xfer += prot_->writeFieldEnd();
  }
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

}} // actor::cpp2
namespace apache { namespace thrift {

}} // apache::thrift