/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ServiceApi.h"

#include "ServiceApi.tcc"

namespace actor { namespace cpp2 {

}} // actor::cpp2
namespace apache { namespace thrift {

}} // apache::thrift