/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "Service_types.h"
#include <thrift/lib/cpp2/protocol/Protocol.h>
namespace actor { namespace cpp2 {

class ServiceConstants {
 public:
  ServiceConstants() {}
};

extern const ServiceConstants g_Service_constants;

}} // actor::cpp2