/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Service_constants.h"

namespace actor { namespace cpp2 {

const ServiceConstants g_Service_constants;

}} // actor::cpp2