/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "TestService.h"

#include <thrift/lib/cpp/TApplicationException.h>

namespace actor { namespace cpp2 {

template <typename ProtocolIn_, typename ProtocolOut_>
void TestServiceAsyncProcessor::_processInThread_reqResp(std::unique_ptr<apache::thrift::ResponseChannel::Request> req, std::unique_ptr<folly::IOBuf> buf, std::unique_ptr<ProtocolIn_> iprot, apache::thrift::Cpp2RequestContext* ctx, apache::thrift::async::TEventBase* eb, apache::thrift::concurrency::ThreadManager* tm) {
  auto pri = iface_->getprio_reqResp(ctx);
  processInThread<ProtocolIn_, ProtocolOut_>(std::move(req), std::move(buf),std::move(iprot), ctx, eb, tm, pri, false, &TestServiceAsyncProcessor::process_reqResp<ProtocolIn_, ProtocolOut_>, this);
}

template <typename ProtocolIn_, typename ProtocolOut_>
void TestServiceAsyncProcessor::process_reqResp(std::unique_ptr<apache::thrift::ResponseChannel::Request> req, std::unique_ptr<folly::IOBuf> buf, std::unique_ptr<ProtocolIn_> iprot,apache::thrift::Cpp2RequestContext* ctx,apache::thrift::async::TEventBase* eb, apache::thrift::concurrency::ThreadManager* tm) {
  // make sure getConnectionContext is null
  // so async calls don't accidentally use it
  iface_->setConnectionContext(nullptr);
  TestService_reqResp_pargs args;
  std::unique_ptr<std::string> uarg_req(new std::string());
  args.req = uarg_req.get();
  std::unique_ptr<apache::thrift::ContextStack> c(this->getContextStack(this->getServiceName(), "TestService.reqResp", ctx));
  try {
    deserializeRequest(args, buf.get(), iprot.get(), c.get());
  }
  catch (const std::exception& ex) {
    ProtocolOut_ prot;
    if (req) {
      LOG(ERROR) << ex.what() << " in function reqResp";
      apache::thrift::TApplicationException x(apache::thrift::TApplicationException::TApplicationExceptionType::PROTOCOL_ERROR, ex.what());
      folly::IOBufQueue queue = serializeException("reqResp", &prot, iprot->getSeqId(), nullptr, x);
      queue.append(apache::thrift::transport::THeader::transform(queue.move(), ctx->getTransforms(), ctx->getMinCompressBytes()));
      auto queue_mw = folly::makeMoveWrapper(std::move(queue));
      auto req_mw = folly::makeMoveWrapper(std::move(req));
      eb->runInEventBaseThread([=]() mutable {
        (*req_mw)->sendReply(queue_mw->move());
      }
      );
      return;
    }
    else {
      LOG(ERROR) << ex.what() << " in oneway function reqResp";
    }
  }
  std::unique_ptr<apache::thrift::HandlerCallback<std::unique_ptr<std::string>>> callback(new apache::thrift::HandlerCallback<std::unique_ptr<std::string>>(std::move(req), std::move(c), return_reqResp<ProtocolIn_,ProtocolOut_>, throw_reqResp<ProtocolIn_, ProtocolOut_>, throw_wrapped_reqResp<ProtocolIn_, ProtocolOut_>, iprot->getSeqId(), eb, tm, ctx));
  if (!callback->isRequestActive()) {
    callback.release()->deleteInThread();
    return;
  }
  ctx->setStartedProcessing();
  iface_->async_tm_reqResp(std::move(callback), std::move(uarg_req));
}

template <class ProtocolIn_, class ProtocolOut_>
folly::IOBufQueue TestServiceAsyncProcessor::return_reqResp(int32_t protoSeqId, std::unique_ptr<apache::thrift::ContextStack> ctx, std::string const& _return) {
  ProtocolOut_ prot;
  TestService_reqResp_presult result;
  result.success = const_cast<std::string*>(&_return);
  result.__isset.success = true;
  return serializeResponse("reqResp", &prot, protoSeqId, ctx.get(), result);
}

template <class ProtocolIn_, class ProtocolOut_>
void TestServiceAsyncProcessor::throw_reqResp(std::unique_ptr<apache::thrift::ResponseChannel::Request> req,int32_t protoSeqId,std::unique_ptr<apache::thrift::ContextStack> ctx,std::exception_ptr ep,apache::thrift::Cpp2RequestContext* reqCtx) {
  ProtocolOut_ prot;
  try {
    std::rethrow_exception(ep);
  }
  catch (const std::exception& e) {
    if (req) {
      LOG(ERROR) << folly::exceptionStr(e).toStdString() << " in function reqResp";
      apache::thrift::TApplicationException x(folly::exceptionStr(e).toStdString());
      ctx->userException(folly::demangle(typeid(e)).toStdString());
      folly::IOBufQueue queue = serializeException("reqResp", &prot, protoSeqId, ctx.get(), x);
      queue.append(apache::thrift::transport::THeader::transform(queue.move(), reqCtx->getTransforms(), reqCtx->getMinCompressBytes()));
      req->sendReply(queue.move());
      return;
    }
    else {
      LOG(ERROR) << folly::exceptionStr(e).toStdString() << " in oneway function reqResp";
    }
  }
  catch (...) {
    if (req) {
      LOG(ERROR) << "<unknown exception>" << " in function reqResp";
      apache::thrift::TApplicationException x("<unknown exception>");
      folly::IOBufQueue queue = serializeException("reqResp", &prot, protoSeqId, nullptr, x);
      queue.append(apache::thrift::transport::THeader::transform(queue.move(), reqCtx->getTransforms(), reqCtx->getMinCompressBytes()));
      req->sendReply(queue.move());
      return;
    }
    else {
      LOG(ERROR) << "<unknown exception>" << " in oneway function reqResp";
    }
  }
}

template <class ProtocolIn_, class ProtocolOut_>
void TestServiceAsyncProcessor::throw_wrapped_reqResp(std::unique_ptr<apache::thrift::ResponseChannel::Request> req,int32_t protoSeqId,std::unique_ptr<apache::thrift::ContextStack> ctx,folly::exception_wrapper ew,apache::thrift::Cpp2RequestContext* reqCtx) {
  if (!ew) {
    return;
  }
  ProtocolOut_ prot;
   {
    if (req) {
      LOG(ERROR) << ew.what().toStdString() << " in function reqResp";
      apache::thrift::TApplicationException x(ew.what().toStdString());
      ctx->userException(ew.class_name().toStdString());
      folly::IOBufQueue queue = serializeException("reqResp", &prot, protoSeqId, ctx.get(), x);
      queue.append(apache::thrift::transport::THeader::transform(queue.move(), reqCtx->getTransforms(), reqCtx->getMinCompressBytes()));
      req->sendReply(queue.move());
      return;
    }
    else {
      LOG(ERROR) << ew.what().toStdString() << " in oneway function reqResp";
    }
  }
}

template <typename ProtocolIn_, typename ProtocolOut_>
void TestServiceAsyncProcessor::_processInThread_asyncReq(std::unique_ptr<apache::thrift::ResponseChannel::Request> req, std::unique_ptr<folly::IOBuf> buf, std::unique_ptr<ProtocolIn_> iprot, apache::thrift::Cpp2RequestContext* ctx, apache::thrift::async::TEventBase* eb, apache::thrift::concurrency::ThreadManager* tm) {
  auto pri = iface_->getprio_asyncReq(ctx);
  processInThread<ProtocolIn_, ProtocolOut_>(std::move(req), std::move(buf),std::move(iprot), ctx, eb, tm, pri, true, &TestServiceAsyncProcessor::process_asyncReq<ProtocolIn_, ProtocolOut_>, this);
}

template <typename ProtocolIn_, typename ProtocolOut_>
void TestServiceAsyncProcessor::process_asyncReq(std::unique_ptr<apache::thrift::ResponseChannel::Request> req, std::unique_ptr<folly::IOBuf> buf, std::unique_ptr<ProtocolIn_> iprot,apache::thrift::Cpp2RequestContext* ctx,apache::thrift::async::TEventBase* eb, apache::thrift::concurrency::ThreadManager* tm) {
  // make sure getConnectionContext is null
  // so async calls don't accidentally use it
  iface_->setConnectionContext(nullptr);
  TestService_asyncReq_pargs args;
  int64_t uarg_id{0};
  args.id = &uarg_id;
  std::unique_ptr<std::string> uarg_payload(new std::string());
  args.payload = uarg_payload.get();
  std::unique_ptr<apache::thrift::ContextStack> c(this->getContextStack(this->getServiceName(), "TestService.asyncReq", ctx));
  try {
    deserializeRequest(args, buf.get(), iprot.get(), c.get());
  }
  catch (const std::exception& ex) {
    LOG(ERROR) << ex.what() << " in function noResponse";
    return;
  }
  std::unique_ptr<apache::thrift::HandlerCallbackBase> callback(new apache::thrift::HandlerCallbackBase(std::move(req), std::move(c), nullptr, nullptr, eb, tm, ctx));
  ctx->setStartedProcessing();
  iface_->async_tm_asyncReq(std::move(callback), *args.id, std::move(uarg_payload));
}

template <typename ProtocolIn_, typename ProtocolOut_>
void TestServiceAsyncProcessor::_processInThread_asyncResp(std::unique_ptr<apache::thrift::ResponseChannel::Request> req, std::unique_ptr<folly::IOBuf> buf, std::unique_ptr<ProtocolIn_> iprot, apache::thrift::Cpp2RequestContext* ctx, apache::thrift::async::TEventBase* eb, apache::thrift::concurrency::ThreadManager* tm) {
  auto pri = iface_->getprio_asyncResp(ctx);
  processInThread<ProtocolIn_, ProtocolOut_>(std::move(req), std::move(buf),std::move(iprot), ctx, eb, tm, pri, true, &TestServiceAsyncProcessor::process_asyncResp<ProtocolIn_, ProtocolOut_>, this);
}

template <typename ProtocolIn_, typename ProtocolOut_>
void TestServiceAsyncProcessor::process_asyncResp(std::unique_ptr<apache::thrift::ResponseChannel::Request> req, std::unique_ptr<folly::IOBuf> buf, std::unique_ptr<ProtocolIn_> iprot,apache::thrift::Cpp2RequestContext* ctx,apache::thrift::async::TEventBase* eb, apache::thrift::concurrency::ThreadManager* tm) {
  // make sure getConnectionContext is null
  // so async calls don't accidentally use it
  iface_->setConnectionContext(nullptr);
  TestService_asyncResp_pargs args;
  int64_t uarg_id{0};
  args.id = &uarg_id;
  std::unique_ptr<std::string> uarg_payload(new std::string());
  args.payload = uarg_payload.get();
  std::unique_ptr<apache::thrift::ContextStack> c(this->getContextStack(this->getServiceName(), "TestService.asyncResp", ctx));
  try {
    deserializeRequest(args, buf.get(), iprot.get(), c.get());
  }
  catch (const std::exception& ex) {
    LOG(ERROR) << ex.what() << " in function noResponse";
    return;
  }
  std::unique_ptr<apache::thrift::HandlerCallbackBase> callback(new apache::thrift::HandlerCallbackBase(std::move(req), std::move(c), nullptr, nullptr, eb, tm, ctx));
  ctx->setStartedProcessing();
  iface_->async_tm_asyncResp(std::move(callback), *args.id, std::move(uarg_payload));
}

template <typename Protocol_>
void TestServiceAsyncClient::reqRespT(Protocol_* prot, const apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const std::string& req) {
  std::unique_ptr<apache::thrift::ContextStack> ctx = this->getContextStack(this->getServiceName(), "TestService.reqResp", connectionContext_.get());
  TestService_reqResp_pargs args;
  args.req = const_cast<std::string*>(&req);
  size_t bufSize = args.serializedSizeZC(prot);
  bufSize += prot->serializedMessageSize("reqResp");
  folly::IOBufQueue queue(folly::IOBufQueue::cacheChainLength());
  prot->setOutput(&queue, bufSize);
  auto guard = folly::makeGuard([&]{prot->setOutput(nullptr);});
  try {
    ctx->preWrite();
    prot->writeMessageBegin("reqResp", apache::thrift::T_CALL, 0);
    args.write(prot);
    prot->writeMessageEnd();
    ::apache::thrift::SerializedMessage smsg;
    smsg.protocolType = prot->protocolType();
    smsg.buffer = queue.front();
    ctx->onWriteData(smsg);
    ctx->postWrite(queue.chainLength());
  } catch(apache::thrift::TException &ex) {
    ctx->handlerError();
    throw;
  }
  auto eb = this->channel_->getEventBase();
  if(!eb || eb->isInEventBaseThread()) {
    this->channel_->sendRequest(rpcOptions, std::move(callback), std::move(ctx), queue.move());
  }
  else {
    auto mvCb = folly::makeMoveWrapper(std::move(callback));
    auto mvCtx = folly::makeMoveWrapper(std::move(ctx));
    auto mvBuf = folly::makeMoveWrapper(queue.move());
    eb->runInEventBaseThread([this, rpcOptions, mvCb, mvCtx, mvBuf] () mutable {
      this->channel_->sendRequest(rpcOptions, std::move(*mvCb), std::move(*mvCtx), std::move(*mvBuf));
    }
    );
  }
}

template <typename Protocol_>
folly::exception_wrapper TestServiceAsyncClient::recv_wrapped_reqRespT(Protocol_* prot, std::string& _return, ::apache::thrift::ClientReceiveState& state) {
  if (state.isException()) {
    return state.exceptionWrapper();
  }
  prot->setInput(state.buf());
  auto guard = folly::makeGuard([&] {prot->setInput(nullptr);});
  apache::thrift::ContextStack* ctx = state.ctx();
  std::string fname;
  int32_t protoSeqId = 0;
  apache::thrift::MessageType mtype;
  ctx->preRead();
  folly::exception_wrapper interior_ew;
  auto caught_ew = folly::try_and_catch<apache::thrift::TException, apache::thrift::protocol::TProtocolException>([&]() {
    prot->readMessageBegin(fname, mtype, protoSeqId);
    if (mtype == apache::thrift::T_EXCEPTION) {
      apache::thrift::TApplicationException x;
      x.read(prot);
      prot->readMessageEnd();
      interior_ew = folly::make_exception_wrapper<apache::thrift::TApplicationException>(x);
      return; // from try_and_catch
    }
    if (mtype != apache::thrift::T_REPLY) {
      prot->skip(apache::thrift::protocol::T_STRUCT);
      prot->readMessageEnd();
      interior_ew = folly::make_exception_wrapper<apache::thrift::TApplicationException>(apache::thrift::TApplicationException::TApplicationExceptionType::INVALID_MESSAGE_TYPE);
      return; // from try_and_catch
    }
    if (fname.compare("reqResp") != 0) {
      prot->skip(apache::thrift::protocol::T_STRUCT);
      prot->readMessageEnd();
      interior_ew = folly::make_exception_wrapper<apache::thrift::TApplicationException>(apache::thrift::TApplicationException::TApplicationExceptionType::WRONG_METHOD_NAME);
      return; // from try_and_catch
    }
    ::apache::thrift::SerializedMessage smsg;
    smsg.protocolType = prot->protocolType();
    smsg.buffer = state.buf();
    ctx->onReadData(smsg);
    TestService_reqResp_presult result;
    result.success = &_return;
    result.read(prot);
    prot->readMessageEnd();
    ctx->postRead(state.buf()->length());
    if (result.__isset.success) {
      // _return pointer has been filled
      return; // from try_and_catch
    }
    else {
      interior_ew = folly::make_exception_wrapper<apache::thrift::TApplicationException>(apache::thrift::TApplicationException::TApplicationExceptionType::MISSING_RESULT, "failed: unknown result");
      return; // from try_and_catch
    }
  }
  );
  if (interior_ew || caught_ew) {
    ctx->handlerError();
    return interior_ew ? interior_ew : caught_ew;
  }
  return folly::exception_wrapper();
}

template <typename Protocol_>
void TestServiceAsyncClient::recv_reqRespT(Protocol_* prot, std::string& _return, ::apache::thrift::ClientReceiveState& state) {
  auto ew = recv_wrapped_reqRespT(prot, _return, state);
  if (ew) {
    ew.throwException();
  }
}

template <typename Protocol_>
void TestServiceAsyncClient::asyncReqT(Protocol_* prot, const apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, int64_t id, const std::string& payload) {
  std::unique_ptr<apache::thrift::ContextStack> ctx = this->getContextStack(this->getServiceName(), "TestService.asyncReq", connectionContext_.get());
  TestService_asyncReq_pargs args;
  args.id = &id;
  args.payload = const_cast<std::string*>(&payload);
  size_t bufSize = args.serializedSizeZC(prot);
  bufSize += prot->serializedMessageSize("asyncReq");
  folly::IOBufQueue queue(folly::IOBufQueue::cacheChainLength());
  prot->setOutput(&queue, bufSize);
  auto guard = folly::makeGuard([&]{prot->setOutput(nullptr);});
  try {
    ctx->preWrite();
    prot->writeMessageBegin("asyncReq", apache::thrift::T_CALL, 0);
    args.write(prot);
    prot->writeMessageEnd();
    ::apache::thrift::SerializedMessage smsg;
    smsg.protocolType = prot->protocolType();
    smsg.buffer = queue.front();
    ctx->onWriteData(smsg);
    ctx->postWrite(queue.chainLength());
  } catch(apache::thrift::TException &ex) {
    ctx->handlerError();
    throw;
  }
  auto eb = this->channel_->getEventBase();
  if(!eb || eb->isInEventBaseThread()) {
    ctx->asyncComplete();
    this->channel_->sendOnewayRequest(rpcOptions, std::move(callback), std::move(ctx), queue.move());
  }
  else {
    auto mvCb = folly::makeMoveWrapper(std::move(callback));
    auto mvCtx = folly::makeMoveWrapper(std::move(ctx));
    auto mvBuf = folly::makeMoveWrapper(queue.move());
    eb->runInEventBaseThread([this, rpcOptions, mvCb, mvCtx, mvBuf] () mutable {
      (*mvCtx)->asyncComplete();
      this->channel_->sendOnewayRequest(rpcOptions, std::move(*mvCb), std::move(*mvCtx), std::move(*mvBuf));
    }
    );
  }
}

template <typename Protocol_>
void TestServiceAsyncClient::asyncRespT(Protocol_* prot, const apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, int64_t id, const std::string& payload) {
  std::unique_ptr<apache::thrift::ContextStack> ctx = this->getContextStack(this->getServiceName(), "TestService.asyncResp", connectionContext_.get());
  TestService_asyncResp_pargs args;
  args.id = &id;
  args.payload = const_cast<std::string*>(&payload);
  size_t bufSize = args.serializedSizeZC(prot);
  bufSize += prot->serializedMessageSize("asyncResp");
  folly::IOBufQueue queue(folly::IOBufQueue::cacheChainLength());
  prot->setOutput(&queue, bufSize);
  auto guard = folly::makeGuard([&]{prot->setOutput(nullptr);});
  try {
    ctx->preWrite();
    prot->writeMessageBegin("asyncResp", apache::thrift::T_CALL, 0);
    args.write(prot);
    prot->writeMessageEnd();
    ::apache::thrift::SerializedMessage smsg;
    smsg.protocolType = prot->protocolType();
    smsg.buffer = queue.front();
    ctx->onWriteData(smsg);
    ctx->postWrite(queue.chainLength());
  } catch(apache::thrift::TException &ex) {
    ctx->handlerError();
    throw;
  }
  auto eb = this->channel_->getEventBase();
  if(!eb || eb->isInEventBaseThread()) {
    ctx->asyncComplete();
    this->channel_->sendOnewayRequest(rpcOptions, std::move(callback), std::move(ctx), queue.move());
  }
  else {
    auto mvCb = folly::makeMoveWrapper(std::move(callback));
    auto mvCtx = folly::makeMoveWrapper(std::move(ctx));
    auto mvBuf = folly::makeMoveWrapper(queue.move());
    eb->runInEventBaseThread([this, rpcOptions, mvCb, mvCtx, mvBuf] () mutable {
      (*mvCtx)->asyncComplete();
      this->channel_->sendOnewayRequest(rpcOptions, std::move(*mvCb), std::move(*mvCtx), std::move(*mvBuf));
    }
    );
  }
}

template <class Protocol_>
uint32_t TestService_reqResp_pargs::read(Protocol_* iprot) {
  uint32_t xfer = 0;
  std::string fname;
  apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using apache::thrift::TProtocolException;


  while (true) {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == apache::thrift::protocol::T_STOP) {
      break;
    }
    if (fid == std::numeric_limits<int16_t>::min()) {
      if (fname == "req") {
        fid = 1;
        ftype = apache::thrift::protocol::T_STRING;
      }
    }
    switch (fid) {
      case 1:
      {
        if (ftype == apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary((*const_cast<std::string*>(this->req)));
          this->__isset.req = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      }
      default:
      {
        xfer += iprot->skip(ftype);
        break;
      }
    }
    xfer += iprot->readFieldEnd();
  }
  xfer += iprot->readStructEnd();

  return xfer;
}

template <class Protocol_>
uint32_t TestService_reqResp_pargs::serializedSize(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("TestService_reqResp_pargs");
  xfer += prot_->serializedFieldSize("req", apache::thrift::protocol::T_STRING, 1);
  xfer += prot_->serializedSizeBinary((*const_cast<std::string*>(this->req)));
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t TestService_reqResp_pargs::serializedSizeZC(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("TestService_reqResp_pargs");
  xfer += prot_->serializedFieldSize("req", apache::thrift::protocol::T_STRING, 1);
  xfer += prot_->serializedSizeZCBinary((*const_cast<std::string*>(this->req)));
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t TestService_reqResp_pargs::write(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("TestService_reqResp_pargs");
  xfer += prot_->writeFieldBegin("req", apache::thrift::protocol::T_STRING, 1);
  xfer += prot_->writeBinary((*const_cast<std::string*>(this->req)));
  xfer += prot_->writeFieldEnd();
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

template <class Protocol_>
uint32_t TestService_reqResp_presult::read(Protocol_* iprot) {
  uint32_t xfer = 0;
  std::string fname;
  apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using apache::thrift::TProtocolException;


  while (true) {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == apache::thrift::protocol::T_STOP) {
      break;
    }
    if (fid == std::numeric_limits<int16_t>::min()) {
      if (fname == "success") {
        fid = 0;
        ftype = apache::thrift::protocol::T_STRING;
      }
    }
    switch (fid) {
      case 0:
      {
        if (ftype == apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary((*const_cast<std::string*>(this->success)));
          this->__isset.success = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      }
      default:
      {
        xfer += iprot->skip(ftype);
        break;
      }
    }
    xfer += iprot->readFieldEnd();
  }
  xfer += iprot->readStructEnd();

  return xfer;
}

template <class Protocol_>
uint32_t TestService_reqResp_presult::serializedSize(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("TestService_reqResp_presult");
  if (this->__isset.success) {
    xfer += prot_->serializedFieldSize("success", apache::thrift::protocol::T_STRING, 0);
    xfer += prot_->serializedSizeBinary((*const_cast<std::string*>(this->success)));
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t TestService_reqResp_presult::serializedSizeZC(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("TestService_reqResp_presult");
  if (this->__isset.success) {
    xfer += prot_->serializedFieldSize("success", apache::thrift::protocol::T_STRING, 0);
    xfer += prot_->serializedSizeZCBinary((*const_cast<std::string*>(this->success)));
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t TestService_reqResp_presult::write(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("TestService_reqResp_presult");
  if (this->__isset.success) {
    xfer += prot_->writeFieldBegin("success", apache::thrift::protocol::T_STRING, 0);
    xfer += prot_->writeBinary((*const_cast<std::string*>(this->success)));
    xfer += prot_->writeFieldEnd();
  }
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

template <class Protocol_>
uint32_t TestService_asyncReq_pargs::read(Protocol_* iprot) {
  uint32_t xfer = 0;
  std::string fname;
  apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using apache::thrift::TProtocolException;


  while (true) {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == apache::thrift::protocol::T_STOP) {
      break;
    }
    if (fid == std::numeric_limits<int16_t>::min()) {
      if (fname == "id") {
        fid = 1;
        ftype = apache::thrift::protocol::T_I64;
      }
      else if (fname == "payload") {
        fid = 2;
        ftype = apache::thrift::protocol::T_STRING;
      }
    }
    switch (fid) {
      case 1:
      {
        if (ftype == apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64((*const_cast<int64_t*>(this->id)));
          this->__isset.id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      }
      case 2:
      {
        if (ftype == apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary((*const_cast<std::string*>(this->payload)));
          this->__isset.payload = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      }
      default:
      {
        xfer += iprot->skip(ftype);
        break;
      }
    }
    xfer += iprot->readFieldEnd();
  }
  xfer += iprot->readStructEnd();

  return xfer;
}

template <class Protocol_>
uint32_t TestService_asyncReq_pargs::serializedSize(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("TestService_asyncReq_pargs");
  xfer += prot_->serializedFieldSize("id", apache::thrift::protocol::T_I64, 1);
  xfer += prot_->serializedSizeI64((*const_cast<int64_t*>(this->id)));
  xfer += prot_->serializedFieldSize("payload", apache::thrift::protocol::T_STRING, 2);
  xfer += prot_->serializedSizeBinary((*const_cast<std::string*>(this->payload)));
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t TestService_asyncReq_pargs::serializedSizeZC(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("TestService_asyncReq_pargs");
  xfer += prot_->serializedFieldSize("id", apache::thrift::protocol::T_I64, 1);
  xfer += prot_->serializedSizeI64((*const_cast<int64_t*>(this->id)));
  xfer += prot_->serializedFieldSize("payload", apache::thrift::protocol::T_STRING, 2);
  xfer += prot_->serializedSizeZCBinary((*const_cast<std::string*>(this->payload)));
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t TestService_asyncReq_pargs::write(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("TestService_asyncReq_pargs");
  xfer += prot_->writeFieldBegin("id", apache::thrift::protocol::T_I64, 1);
  xfer += prot_->writeI64((*const_cast<int64_t*>(this->id)));
  xfer += prot_->writeFieldEnd();
  xfer += prot_->writeFieldBegin("payload", apache::thrift::protocol::T_STRING, 2);
  xfer += prot_->writeBinary((*const_cast<std::string*>(this->payload)));
  xfer += prot_->writeFieldEnd();
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

template <class Protocol_>
uint32_t TestService_asyncResp_pargs::read(Protocol_* iprot) {
  uint32_t xfer = 0;
  std::string fname;
  apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using apache::thrift::TProtocolException;


  while (true) {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == apache::thrift::protocol::T_STOP) {
      break;
    }
    if (fid == std::numeric_limits<int16_t>::min()) {
      if (fname == "id") {
        fid = 1;
        ftype = apache::thrift::protocol::T_I64;
      }
      else if (fname == "payload") {
        fid = 2;
        ftype = apache::thrift::protocol::T_STRING;
      }
    }
    switch (fid) {
      case 1:
      {
        if (ftype == apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64((*const_cast<int64_t*>(this->id)));
          this->__isset.id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      }
      case 2:
      {
        if (ftype == apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary((*const_cast<std::string*>(this->payload)));
          this->__isset.payload = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      }
      default:
      {
        xfer += iprot->skip(ftype);
        break;
      }
    }
    xfer += iprot->readFieldEnd();
  }
  xfer += iprot->readStructEnd();

  return xfer;
}

template <class Protocol_>
uint32_t TestService_asyncResp_pargs::serializedSize(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("TestService_asyncResp_pargs");
  xfer += prot_->serializedFieldSize("id", apache::thrift::protocol::T_I64, 1);
  xfer += prot_->serializedSizeI64((*const_cast<int64_t*>(this->id)));
  xfer += prot_->serializedFieldSize("payload", apache::thrift::protocol::T_STRING, 2);
  xfer += prot_->serializedSizeBinary((*const_cast<std::string*>(this->payload)));
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t TestService_asyncResp_pargs::serializedSizeZC(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("TestService_asyncResp_pargs");
  xfer += prot_->serializedFieldSize("id", apache::thrift::protocol::T_I64, 1);
  xfer += prot_->serializedSizeI64((*const_cast<int64_t*>(this->id)));
  xfer += prot_->serializedFieldSize("payload", apache::thrift::protocol::T_STRING, 2);
  xfer += prot_->serializedSizeZCBinary((*const_cast<std::string*>(this->payload)));
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t TestService_asyncResp_pargs::write(Protocol_* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("TestService_asyncResp_pargs");
  xfer += prot_->writeFieldBegin("id", apache::thrift::protocol::T_I64, 1);
  xfer += prot_->writeI64((*const_cast<int64_t*>(this->id)));
  xfer += prot_->writeFieldEnd();
  xfer += prot_->writeFieldBegin("payload", apache::thrift::protocol::T_STRING, 2);
  xfer += prot_->writeBinary((*const_cast<std::string*>(this->payload)));
  xfer += prot_->writeFieldEnd();
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

}} // actor::cpp2
namespace apache { namespace thrift {

}} // apache::thrift